Added functionality to test a specific file

diff --git a/Lex/Makefile b/Lex/Makefile
--- a/Lex/Makefile
+++ b/Lex/Makefile
@@ -1,4 +1,6 @@
-TEST_INPUT_FILES := $(wildcard Tests/*.in)
+TESTS := $(wildcard Tests/*.in)
+
+INPUT_FILES := $(if $(FILE), Tests/$(FILE).in, $(TESTS))
 
 build:
 	flex lexer.l
@@ -11,11 +13,18 @@ clean:
 	rm lex.yy.c
 	rm lexer
 
-test: $(TEST_INPUT_FILES)
+test: $(INPUT_FILES)
 	@make build --quiet
-	@for input_file in $(TEST_INPUT_FILES); do \
+	@sorted_files=$$(echo "$(INPUT_FILES)" | tr ' ' '\n' | sort -V | tr '\n' ' '); \
+	for input_file in $$sorted_files; do \
 		output_file=Tests/$$(basename $$input_file .in).out; \
-		(./lexer < $$input_file) | diff -q $$output_file - > /dev/null && \
-			echo "\033[32m$$(basename $$input_file .in) [ PASSED ]\033[0m" || \
-			(echo "\033[31m$$(basename $$input_file .in) [ FAILED ]\033[0m" && exit 1); \
-	done
+		if !(./lexer < $$input_file | diff --color=auto $$output_file -); then \
+			echo "\033[31m$$(basename $$input_file .in) [ FAILED ]\033[0m"; \
+			FAIL=1; \
+		else \
+			echo "\033[32m$$(basename $$input_file .in) [ PASSED ]\033[0m"; \
+		fi; \
+	done; \
+	if [ -n "$$FAIL" ]; then \
+		exit 1; \
+	fi
